services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./cmd/auth-service/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - db
    environment:
      - DATABASE_URL="postgres://auth_user:auth_pass@db:5432/auth_db?sslmode=disable"

  api-gateway:
    container_name: api-gateway
    build: 
      context: .
      dockerfile: ./cmd/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service

  db:
    container_name: db
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "auth_user", "-d", "auth_db"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
