services:
  postgres-test:
    image: postgres:17.2
    container_name: auth_db_test
    environment:
      POSTGRES_DB: auth_test_db
      POSTGRES_USER: auth_test_user
      POSTGRES_PASSWORD: auth_test_pass
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_test_user -d auth_test_db" ]
      interval: 5s
      retries: 5
